let Musique_1 = 0
let Choix = 1
let Condition = 0
// Sélection 
basic.forever(function () {
    if (Choix == 1 && input.logoIsPressed()) {
        Musique_1 = 1
        Condition = 1
    }
    if (Choix == 2 && input.logoIsPressed()) {
        Musique_1 = 2
        Condition = 1
    }
    if (Choix == 3 && input.logoIsPressed()) {
        Musique_1 = 3
        Condition = 1
    }
})
basic.forever(function () {
    if (Musique_1 == 1) {
        Musique_1 = 0
        music.playTone(349, music.beat(BeatFraction.Half))
        basic.pause(500)
        music.playTone(392, music.beat(BeatFraction.Half))
        basic.pause(500)
        music.playTone(262, music.beat(BeatFraction.Half))
        basic.pause(300)
        music.playTone(392, music.beat(BeatFraction.Half))
        basic.pause(500)
        music.playTone(440, music.beat(BeatFraction.Half))
        basic.pause(500)
        music.playTone(370, music.beat(BeatFraction.Half))
        music.playTone(466, music.beat(BeatFraction.Half))
        music.playTone(440, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(349, music.beat(BeatFraction.Half))
        basic.pause(500)
        music.playTone(392, music.beat(BeatFraction.Half))
        basic.pause(250)
        music.playTone(262, music.beat(BeatFraction.Half))
        basic.pause(1300)
        music.playTone(262, music.beat(BeatFraction.Half))
        music.playTone(262, music.beat(BeatFraction.Half))
        music.playTone(294, music.beat(BeatFraction.Half))
        music.playTone(349, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(349, music.beat(BeatFraction.Half))
        music.playTone(349, music.beat(BeatFraction.Half))
        basic.pause(500)
        music.playTone(392, music.beat(BeatFraction.Half))
        basic.pause(500)
        music.playTone(262, music.beat(BeatFraction.Half))
        basic.pause(300)
        music.playTone(392, music.beat(BeatFraction.Half))
        basic.pause(500)
        music.playTone(440, music.beat(BeatFraction.Half))
        basic.pause(500)
        music.playTone(523, music.beat(BeatFraction.Half))
        music.playTone(466, music.beat(BeatFraction.Half))
        music.playTone(440, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(349, music.beat(BeatFraction.Half))
        basic.pause(500)
        music.playTone(392, music.beat(BeatFraction.Half))
        basic.pause(1000)
        music.playTone(262, music.beat(BeatFraction.Half))
        basic.pause(1300)
        music.playTone(262, music.beat(BeatFraction.Half))
        music.playTone(262, music.beat(BeatFraction.Half))
        music.playTone(294, music.beat(BeatFraction.Half))
        music.playTone(349, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(349, music.beat(BeatFraction.Half))
        basic.pause(400)
        music.playTone(294, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(330, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(349, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(349, music.beat(BeatFraction.Half))
        basic.pause(200)
        music.playTone(392, music.beat(BeatFraction.Half))
        basic.pause(200)
        music.playTone(330, music.beat(BeatFraction.Half))
        basic.pause(400)
        music.playTone(294, music.beat(BeatFraction.Half))
        music.playTone(262, music.beat(BeatFraction.Half))
        basic.pause(1500)
        music.playTone(294, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(294, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(330, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(349, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(294, music.beat(BeatFraction.Half))
        basic.pause(300)
        music.playTone(262, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(523, music.beat(BeatFraction.Half))
        basic.pause(300)
        music.playTone(523, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(392, music.beat(BeatFraction.Half))
        basic.pause(900)
        music.playTone(294, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(294, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(330, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(349, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(294, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(349, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(392, music.beat(BeatFraction.Half))
        basic.pause(500)
        music.playTone(330, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(294, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(262, music.beat(BeatFraction.Half))
        basic.pause(1100)
        music.playTone(294, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(294, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(330, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(349, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(294, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(262, music.beat(BeatFraction.Half))
        basic.pause(300)
        music.playTone(392, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(392, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(392, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(440, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(392, music.beat(BeatFraction.Half))
        basic.pause(700)
        music.playTone(349, music.beat(BeatFraction.Half))
        basic.pause(900)
        music.playTone(392, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(440, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(349, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(392, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(392, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(392, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(440, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(392, music.beat(BeatFraction.Half))
        basic.pause(300)
        music.playTone(262, music.beat(BeatFraction.Half))
        basic.pause(600)
        music.playTone(294, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(330, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(349, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(294, music.beat(BeatFraction.Half))
        basic.pause(300)
        music.playTone(392, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(440, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(392, music.beat(BeatFraction.Half))
        basic.pause(500)
        music.playTone(262, music.beat(BeatFraction.Half))
        music.playTone(294, music.beat(BeatFraction.Half))
        music.playTone(349, music.beat(BeatFraction.Half))
        music.playTone(294, music.beat(BeatFraction.Half))
        music.playTone(440, music.beat(BeatFraction.Half))
        basic.pause(200)
        music.playTone(440, music.beat(BeatFraction.Half))
        basic.pause(200)
        music.playTone(392, music.beat(BeatFraction.Half))
        basic.pause(500)
        music.playTone(262, music.beat(BeatFraction.Half))
        music.playTone(294, music.beat(BeatFraction.Half))
        music.playTone(349, music.beat(BeatFraction.Half))
        music.playTone(294, music.beat(BeatFraction.Half))
        music.playTone(392, music.beat(BeatFraction.Half))
        basic.pause(200)
        music.playTone(392, music.beat(BeatFraction.Half))
        basic.pause(200)
        music.playTone(349, music.beat(BeatFraction.Half))
        basic.pause(200)
        music.playTone(330, music.beat(BeatFraction.Half))
        music.playTone(294, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(262, music.beat(BeatFraction.Half))
        music.playTone(294, music.beat(BeatFraction.Half))
        music.playTone(349, music.beat(BeatFraction.Half))
        music.playTone(294, music.beat(BeatFraction.Half))
        music.playTone(349, music.beat(BeatFraction.Half))
        basic.pause(300)
        music.playTone(392, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(330, music.beat(BeatFraction.Half))
        basic.pause(200)
        music.playTone(294, music.beat(BeatFraction.Half))
        music.playTone(262, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(262, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(262, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(392, music.beat(BeatFraction.Half))
        basic.pause(300)
        music.playTone(349, music.beat(BeatFraction.Half))
        basic.pause(700)
        music.playTone(262, music.beat(BeatFraction.Half))
        music.playTone(294, music.beat(BeatFraction.Half))
        music.playTone(349, music.beat(BeatFraction.Half))
        music.playTone(294, music.beat(BeatFraction.Half))
        music.playTone(440, music.beat(BeatFraction.Half))
        basic.pause(200)
        music.playTone(392, music.beat(BeatFraction.Half))
        basic.pause(500)
        music.playTone(262, music.beat(BeatFraction.Half))
        music.playTone(294, music.beat(BeatFraction.Half))
        music.playTone(349, music.beat(BeatFraction.Half))
        music.playTone(294, music.beat(BeatFraction.Half))
        music.playTone(523, music.beat(BeatFraction.Half))
        basic.pause(300)
        music.playTone(330, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(349, music.beat(BeatFraction.Half))
        basic.pause(200)
        music.playTone(330, music.beat(BeatFraction.Half))
        music.playTone(294, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(262, music.beat(BeatFraction.Half))
        music.playTone(294, music.beat(BeatFraction.Half))
        music.playTone(349, music.beat(BeatFraction.Half))
        music.playTone(294, music.beat(BeatFraction.Half))
        music.playTone(349, music.beat(BeatFraction.Half))
        basic.pause(300)
        music.playTone(392, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(330, music.beat(BeatFraction.Half))
        basic.pause(200)
        music.playTone(294, music.beat(BeatFraction.Half))
        music.playTone(262, music.beat(BeatFraction.Half))
        basic.pause(300)
        music.playTone(262, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(392, music.beat(BeatFraction.Half))
        basic.pause(300)
        music.playTone(349, music.beat(BeatFraction.Half))
        basic.pause(1300)
        music.playTone(294, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(349, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(294, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(349, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(392, music.beat(BeatFraction.Half))
        basic.pause(700)
        music.playTone(330, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(294, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(262, music.beat(BeatFraction.Half))
        basic.pause(1100)
        music.playTone(294, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(294, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(330, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(349, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(294, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(262, music.beat(BeatFraction.Half))
        basic.pause(500)
        music.playTone(523, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(523, music.beat(BeatFraction.Half))
        basic.pause(100)
        music.playTone(392, music.beat(BeatFraction.Half))
        basic.pause(150)
        music.playTone(440, music.beat(BeatFraction.Half))
        basic.pause(50)
        music.playTone(392, music.beat(BeatFraction.Half))
        basic.pause(50)
        music.playTone(349, music.beat(BeatFraction.Half))
        basic.pause(150)
        music.playTone(294, music.beat(BeatFraction.Half))
        basic.pause(50)
        music.playTone(349, music.beat(BeatFraction.Half))
        basic.pause(50)
        music.playTone(294, music.beat(BeatFraction.Half))
        basic.pause(50)
        music.playTone(349, music.beat(BeatFraction.Half))
        basic.pause(50)
        music.playTone(294, music.beat(BeatFraction.Half))
        basic.pause(50)
        music.playTone(349, music.beat(BeatFraction.Half))
        basic.pause(50)
        music.playTone(392, music.beat(BeatFraction.Half))
        basic.pause(150)
        music.playTone(330, music.beat(BeatFraction.Half))
        basic.pause(50)
        music.playTone(294, music.beat(BeatFraction.Half))
        basic.pause(50)
        music.playTone(262, music.beat(BeatFraction.Half))
        basic.pause(450)
        music.playTone(294, music.beat(BeatFraction.Half))
        basic.pause(50)
        music.playTone(330, music.beat(BeatFraction.Half))
        basic.pause(50)
        music.playTone(349, music.beat(BeatFraction.Half))
        basic.pause(50)
        music.playTone(294, music.beat(BeatFraction.Half))
        basic.pause(50)
        music.playTone(262, music.beat(BeatFraction.Half))
        basic.pause(350)
        music.playTone(392, music.beat(BeatFraction.Half))
        basic.pause(50)
        music.playTone(440, music.beat(BeatFraction.Half))
        basic.pause(50)
        music.playTone(392, music.beat(BeatFraction.Half))
        basic.pause(150)
        music.playTone(392, music.beat(BeatFraction.Half))
        basic.pause(250)
        music.playTone(349, music.beat(BeatFraction.Half))
    }
})
// Musique:2 classique
basic.forever(function () {
    if (Musique_1 == 2) {
        music.playMelody("F E D F - - - - ", 300)
        music.playMelody("F E D F A - - - ", 300)
        music.playMelody("F E D F - - - - ", 300)
        music.playMelody("F E D F A E - - ", 300)
        music.playMelody("F E D F - D E F ", 300)
        music.playMelody("G F - F E - A G ", 300)
        music.playMelody("G A F - E D A G ", 300)
        music.playMelody("G - C5 A - F - D ", 300)
        music.playMelody("E - F D - G E - ", 300)
        Musique_1 = 0
    }
})
// Musique:2 classique
basic.forever(function () {
    if (Musique_1 == 3) {
        music.playMelody("C5 A C5 B A B G D ", 130)
        music.playMelody("E A F G E D G C ", 130)
        music.playMelody("C G C D F B E A ", 130)
        music.playMelody("- A C5 B A B G - ", 130)
        music.playMelody("D E - F G - B A ", 130)
        music.playMelody("- F A - E D - C ", 130)
        music.playMelody("B A F - G F D - ", 130)
        music.playMelody("B F E G F B G C5 ", 130)
        music.playMelody("D C G E F D E C ", 130)
        music.playMelody("E F - F E - E F ", 130)
        music.playMelody("F E D E F E D F ", 130)
        music.playMelody("D D C C E E G G ", 130)
        music.playMelody("E C - E C - E C ", 130)
        music.playMelody("C E A C5 B G E C ", 130)
        music.playMelody("D E C - D E C F ", 130)
        Musique_1 = 0
    }
})
// Affichage
basic.forever(function () {
    basic.showNumber(Choix)
    if (Choix >= 4) {
        Choix = 3
    }
    if (Choix < 1) {
        Choix = 1
    }
})
// Sélection de choix
basic.forever(function () {
    if (input.buttonIsPressed(Button.A)) {
        Choix += -1
    }
    if (input.buttonIsPressed(Button.B)) {
        Choix += 1
    }
    basic.pause(100)
})
